#!/usr/bin/env bash 
#This is a script that displays Best schools 10 times using the if condition 
i=1
while [ "$i" -le 10 ]
do 
	echo "Best School"
	if [ "$i" -eq 9 ]; then 
	echo "Hi"
	fi 
	i=$((i + 1))
done
