#!/usr/bin/env bash
# Script that displays stuff in a directory 

for file in *     # '*' lists all non-hidden files
do
    if [[ "$file" == *-* ]]; then
    
    echo "${file#*-}"
  else
    
    echo "$file"
  fi
done
